CraftHouse.Web/Entities/Product.cs
using System.ComponentModel.DataAnnotations;

namespace CraftHouse.Web.Entities;

public class Product:EntityBase
{
    [Key]
    public int Id { get; set; }

    [Required]
    public string Name { get; set; } = null!;

    [Required]
    public bool IsAvailable { get; set; }
    
    [Required]
    public float Price { get; set; }

    [Required]
    public string Description { get; set; } = null!;

    [Required]
    public int CategoryId { get; set; }

    public Category Category { get; set; } = null!;

    public ICollection<Option> Options { get; set; } = null!;
    public ICollection<OrderItem> OrderItems { get; set; } = null!;
}

CraftHouse.Web/Pages/Admin/Categories.cshtml.cs
using CraftHouse.Web.Data;
using CraftHouse.Web.DTOs;
using CraftHouse.Web.Entities;
using CraftHouse.Web.Infrastructure;
using CraftHouse.Web.Repositories;
using FluentValidation;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CraftHouse.Web.Pages.Admin;

[RequireAuth(UserType.Administrator)]
public class CategoryManagement : PageModel
{
    private readonly ICategoryRepository _categoryRepository;
    private readonly IValidator<Category> _validator;

    public CategoryManagement(ICategoryRepository categoryRepository, IValidator<Category> validator)
    {
        _categoryRepository = categoryRepository;
        _validator = validator;
    }
    
    [BindProperty]
    public CategoryDto CategoryDto { get; set; } = null!;
    public List<Category> Categories { get; set; } = null!;
    public string? Error { get; set; }

    public async Task<IActionResult> OnGet(CancellationToken cancellationToken)
    {
        Categories = await _categoryRepository.GetCategoriesAsync(cancellationToken);

        return Page();
    }
    
    public async Task<IActionResult> OnPostAddCategoryAsync(CancellationToken cancellationToken)
    {
        var isCategoryExisting = await _categoryRepository.CategoryExistsAsync(CategoryDto.Name, cancellationToken);

        if (isCategoryExisting)
        {
            Error = "That named category already exits";
            Categories = await _categoryRepository.GetCategoriesAsync(cancellationToken);
            CategoryDto.Name = "";
            return Page();
        }
        
        var category = CategoryDto.MapToCategory();
        var validationResult = await _validator.ValidateAsync(category, cancellationToken);

        if (!validationResult.IsValid)
        {
            Error = validationResult.Errors.First().ToString();
            Categories = await _categoryRepository.GetCategoriesAsync(cancellationToken);
            CategoryDto.Name = "";
            return Page();
        }
        
        await _categoryRepository.AddCategoryAsync(category, cancellationToken);

        return Redirect("Categories");
    }
}

CraftHouse.Web/Pages/Admin/CategoryPage.cshtml.cs
using Azure.Core;
using CraftHouse.Web.Data;
using CraftHouse.Web.DTOs;
using CraftHouse.Web.Entities;
using CraftHouse.Web.Infrastructure;
using CraftHouse.Web.Repositories;
using FluentValidation;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace CraftHouse.Web.Pages.Admin;

[RequireAuth(UserType.Administrator)]
public class CategoryPage : PageModel
{
    private readonly ICategoryRepository _categoryRepository;
    private readonly IValidator<Category> _validator;

    public CategoryPage(ICategoryRepository categoryRepository, IValidator<Category> validator)
    {
        _categoryRepository = categoryRepository;
        _validator = validator;
    }

    public Category Category { get; set; } = null!;

    [BindProperty]
    public CategoryDeleteModel CategoryDelete { get; set; } = null!;

    [BindProperty]
    public CategoryUpdateModel CategoryUpdate { get; set; } = null!;

    public string? Error { get; set; }

    public async Task<IActionResult> OnGetAsync(int id, CancellationToken cancellationToken)
    {
        var category = await _categoryRepository.GetCategoryWithProducts(id, cancellationToken);
        Category = category ?? throw new NullReferenceException("Category does not exits");

        if (Category is null)
        {
            throw new InvalidOperationException("Category does not exists");
        }

        return Page();
    }

    public async Task<IActionResult> OnPostDeleteAsync(CancellationToken cancellationToken)
    {
        var category = await _categoryRepository.GetCategoryByIdAsync(CategoryDelete.Id, cancellationToken);
        if (category is null)
        {
            throw new NullReferenceException("Category does not exists");
        }

        var isCategoryEmpty = await _categoryRepository.IsCategoryEmptyAsync(CategoryDelete.Id, cancellationToken);

        if (isCategoryEmpty)
        {
            throw new InvalidOperationException("Cannot delete non empty category");
        }

        await _categoryRepository.DeleteCategoryAsync(category, cancellationToken);

        return RedirectToPage("/Admin/Categories");
    }

    public async Task<IActionResult> OnPostUpdateAsync(CancellationToken cancellationToken)
    {
        var category = await _categoryRepository.GetCategoryByIdAsync(CategoryUpdate.Id, cancellationToken);
        if (category is null)
        {
            throw new NullReferenceException("Category does not exists");
        }

        var isCategoryNameTaken = await _categoryRepository
            .CategoryExistsAsync(CategoryUpdate.Name, cancellationToken);

        if (isCategoryNameTaken)
        {
            throw new InvalidOperationException("Category name is taken");
        }

        var categoryDto = new CategoryDto
        {
            Name = CategoryUpdate.Name
        };
        var toCheck = categoryDto.MapToCategory();
        var validationResult = await _validator.ValidateAsync(toCheck, cancellationToken);

        if (!validationResult.IsValid)
        {
            Error = validationResult.Errors.First().ToString();
            var cat = await _categoryRepository.GetCategoryWithProducts(category.Id, cancellationToken);
            Category = cat ?? throw new NullReferenceException("Category does not exists");
            return Page();
        }

        category.Name = CategoryUpdate.Name;

        await _categoryRepository.UpdateCategoryAsync(category, cancellationToken);

        return Redirect("/admin/category/" + category.Id);
    }
}

public record CategoryDeleteModel(int Id);

public record CategoryUpdateModel(int Id, string Name);

CraftHouse.Web/Pages/Admin/OptionValuesManagement.cshtml.cs
using CraftHouse.Web.DTOs;
using CraftHouse.Web.Entities;
using CraftHouse.Web.Infrastructure;
using CraftHouse.Web.Repositories;
using FluentValidation;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CraftHouse.Web.Pages.Admin;

[RequireAuth(UserType.Administrator)]
public class OptionValuesManagement : PageModel
{
    private readonly IOptionValueRepository _optionValueRepository;
    private readonly IOptionRepository _optionRepository;
    private readonly IValidator<OptionValue> _optionValueValidator;
    private readonly IValidator<Option> _optionValidator;

    public OptionValuesManagement(IOptionValueRepository optionValueRepository, IOptionRepository optionRepository,
        IValidator<OptionValue> optionValueValidator, IValidator<Option> optionValidator)
    {
        _optionValueRepository = optionValueRepository;
        _optionRepository = optionRepository;
        _optionValueValidator = optionValueValidator;
        _optionValidator = optionValidator;
    }

    [BindProperty]
    public int OptionId { get; set; }

    [BindProperty]
    public string OptionValue { get; set; } = null!;

    [BindProperty]
    public string OldOptionValue { get; set; } = null!;

    [BindProperty]
    public float OptionPrice { get; set; }

    [BindProperty]
    public string OptionName { get; set; } = null!;

    [BindProperty]
    public OptionValueDto OptionValueDto { get; set; } = null!;

    public OptionDto OptionDto { get; set; } = null!;

    public List<OptionValue> OptionValues { get; set; } = null!;

    public Option Option { get; set; } = null!;

    public List<string>? Errors { get; set; }

    public async Task OnGet(int optionId, CancellationToken cancellationToken)
    {
        OptionId = optionId;
        var option = await _optionRepository.GetOptionByIdAsync(OptionId, cancellationToken);

        Option = option ?? throw new NullReferenceException("Option does not exists");

        OptionValues = await _optionValueRepository.GetOptionValuesByOptionIdAsync(OptionId, cancellationToken);
        OptionName = Option.Name;
    }

    public async Task<IActionResult> OnPostRemoveAsync(CancellationToken cancellationToken)
    {
        var optionValueToDelete =
            await _optionValueRepository.GetOptionValueAsync(OptionId, OptionValue, cancellationToken);

        if (optionValueToDelete is null)
        {
            throw new NullReferenceException("Option value does not exists");
        }

        await _optionValueRepository.RemoveOptionValueAsync(OptionId, OptionValue, cancellationToken);

        return Redirect($"/admin/OptionValuesManagement/{OptionId}");
    }

    public async Task<IActionResult> OnPostOptionNameAsync(CancellationToken cancellationToken)
    {
        var option = await _optionRepository.GetOptionByIdAsync(OptionId, cancellationToken);

        if (option is null)
        {
            throw new NullReferenceException("Option does not exists");
        }

        OptionDto = new OptionDto
        {
            Name = OptionName,
            MaxOccurs = option.MaxOccurs,
            ProductId = option.ProductId
        };
        var toCheck = OptionDto.MapToOption();
        var validationResult = await _optionValidator.ValidateAsync(toCheck, cancellationToken);

        if (!validationResult.IsValid)
        {
            Errors = validationResult.Errors.Select(x => x.ErrorMessage).ToList();
            OptionValues = await _optionValueRepository.GetOptionValuesByOptionIdAsync(OptionId, cancellationToken);
            Option = option;
            return Page();
        }

        option.Name = OptionName;
        await _optionRepository.UpdateOptionAsync(option, cancellationToken);

        return Redirect($"/admin/OptionValuesManagement/{OptionId}");
    }

    public async Task<IActionResult> OnPostNewValueAsync(CancellationToken cancellationToken)
    {
        var option = await _optionRepository.GetOptionByIdAsync(OptionId, cancellationToken);

        if (option is null)
        {
            throw new NullReferenceException("Option does not exists");
        }

        OptionValueDto.OptionId = OptionId;
        var optionValue = OptionValueDto.MapToOptionValue();
        var validationResult = await _optionValueValidator.ValidateAsync(optionValue, cancellationToken);

        if (!validationResult.IsValid)
        {
            Errors = validationResult.Errors.Select(x => x.ErrorMessage).ToList();
            OptionValues = await _optionValueRepository.GetOptionValuesByOptionIdAsync(OptionId, cancellationToken);
            Option = option;
            return Page();
        }

        await _optionValueRepository.AddNewOptionValueAsync(optionValue, cancellationToken);

        return Redirect($"/admin/OptionValuesManagement/{OptionId}");
    }

    public async Task<IActionResult> OnPostUpdateValueAsync(CancellationToken cancellationToken)
    {
        var value = await _optionValueRepository.GetOptionValueAsync(OptionId, OldOptionValue, cancellationToken);

        if (value is null)
        {
            throw new NullReferenceException("Option value does not exists");
        }

        OptionValueDto.Value = OptionValue;
        OptionValueDto.Price = OptionPrice;
        OptionValueDto.OptionId = OptionId;
        var optionValue = OptionValueDto.MapToOptionValue();
        var validationResult = await _optionValueValidator.ValidateAsync(optionValue, cancellationToken);

        if (!validationResult.IsValid)
        {
            Errors = validationResult.Errors.Select(x => x.ErrorMessage).ToList();
            OptionValues = await _optionValueRepository.GetOptionValuesByOptionIdAsync(OptionId, cancellationToken);
            Option = await _optionRepository.GetOptionByIdAsync(OptionId, cancellationToken) ??
                     throw new InvalidOperationException("Option does not exists");
            OptionValueDto.Value = "";
            OptionValueDto.Price = 0;
            return Page();
        }

        await _optionValueRepository.UpdateOptionValueFieldsAsync(OptionId, OldOptionValue, OptionValue, OptionPrice,
            cancellationToken);

        return Redirect($"/admin/OptionValuesManagement/{OptionId}");
    }
}

CraftHouse.Web/Pages/Admin/OptionsManagement.cshtml.cs
using CraftHouse.Web.DTOs;
using CraftHouse.Web.Entities;
using CraftHouse.Web.Infrastructure;
using CraftHouse.Web.Repositories;
using FluentValidation;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CraftHouse.Web.Pages.Admin;

[RequireAuth(UserType.Administrator)]
public class OptionsManagement : PageModel
{
    private readonly IOptionRepository _optionRepository;
    private readonly IProductRepository _productRepository;
    private readonly IValidator<Option> _optionValidator;
    private readonly IValidator<OptionValue> _optionValueValidator;
    private readonly ILogger<OptionsManagement> _logger;

    public OptionsManagement(IOptionRepository optionRepository, IProductRepository productRepository,
        IValidator<Option> optionValidator, IValidator<OptionValue> optionValueValidator,
        ILogger<OptionsManagement> logger)
    {
        _optionRepository = optionRepository;
        _productRepository = productRepository;
        _optionValidator = optionValidator;
        _optionValueValidator = optionValueValidator;
        _logger = logger;
    }

    [BindProperty]
    public string Name { get; set; } = null!;

    [BindProperty]
    public int OptionId { get; set; }

    [BindProperty]
    public int ProductId { get; set; }

    [BindProperty]
    public int MaxOccurs { get; set; }

    [BindProperty]
    public List<string> OptionValues { get; set; } = null!;

    [BindProperty]
    public List<float> OptionPrices { get; set; } = null!;

    public List<Option> ExistingOptions { get; set; } = null!;

    public int OptionNumber { get; set; }

    public List<string>? Errors { get; set; }

    public Product Product { get; set; } = null!;

    public async Task<IActionResult> OnGet(int productId, int optionNumber, CancellationToken cancellationToken)
    {
        var product = await _productRepository.GetProductByIdAsync(productId, cancellationToken);
        Product = product ?? throw new NullReferenceException("Product does not exists");

        optionNumber = optionNumber < 1 ? 1 : optionNumber;

        OptionNumber = optionNumber;
        ExistingOptions = await _optionRepository.GetOptionsByProductIdAsync(Product.Id, cancellationToken);
        return Page();
    }

    public async Task<IActionResult> OnPostOptionAsync(CancellationToken cancellationToken)
    {
        var product = await _productRepository.GetProductByIdAsync(ProductId, cancellationToken);
        Product = product ?? throw new NullReferenceException("Product does not exists");
        
        foreach (var data in OptionValues.Select((value, i) => new {i , value}))
        {
            var optionValueDto = new OptionValueDto()
            {
                Value = data.value,
                Price = OptionPrices[data.i],
                OptionId = 1
            };
            var optionValue = optionValueDto.MapToOptionValue();
            var validationResult = await _optionValueValidator.ValidateAsync(optionValue, cancellationToken);

            if (validationResult.IsValid) continue;
            ExistingOptions = await _optionRepository.GetOptionsByProductIdAsync(Product.Id, cancellationToken);
            Errors = validationResult.Errors.Select(x => x.ErrorMessage).ToList();
            return Page();
        }

        var optionDto = new OptionDto()
        {
            Name = Name,
            MaxOccurs = MaxOccurs,
            ProductId = Product.Id
        };

        var option = optionDto.MapToOption();
        var optionValidationResult = await _optionValidator.ValidateAsync(option, cancellationToken);
        if (!optionValidationResult.IsValid)
        {
            ExistingOptions = await _optionRepository.GetOptionsByProductIdAsync(Product.Id, cancellationToken);
            Errors = optionValidationResult.Errors.Select(x => x.ErrorMessage).ToList();
            return Page();
        }

        ICollection<OptionValue> optionValues =
            OptionValues.Select((t, i) => new OptionValue() { Value = t, Price = OptionPrices[i] }).ToList();

        option.OptionValues = optionValues;

        await _optionRepository.AddOptionAsync(option, cancellationToken);

        return Redirect($"/admin/OptionsManagement/{Product.Id}?optionNumber={1}");
    }

    [BindProperty]
    public DeleteOptionModel DeleteOptionModel { get; set; } = null!;

    public async Task<IActionResult> OnPostRemoveAsync(CancellationToken cancellationToken)
    {
        var option = await _optionRepository.GetOptionByIdAsync(DeleteOptionModel.Id, cancellationToken);
        if (option is null)
        {
            _logger.LogWarning("Trying to delete non existing option with option Id: {@optionID}", DeleteOptionModel.Id);
            throw new NullReferenceException("Option not found");
        }

        await _optionRepository.DeleteOptionAsync(option, cancellationToken);

        return Redirect($"/admin/OptionsManagement/{ProductId}?optionNumber={1}");
    }
}

public record DeleteOptionModel(int Id);

CraftHouse.Web/Pages/Admin/Categories.cshtml
@page "{handler?}"
@model CategoryManagement

@{
    ViewData["title"] = "Categories";
    ViewData["styles"] = "categories";
}

@if (Model.Error != null)
{
    <div class="error">@Model.Error</div>
}

<h1>New category</h1>
<form class="form" method="post" asp-page-handler="AddCategory" class="categoryManagement__form">
    <label for="addCategoryName">Name for new category</label>
    <input type="text" id="addCategoryName" asp-for="@Model.CategoryDto.Name"/>

    <input class="button button--teal" type="submit" value="Add"/>
</form>

<h1>Existing categories</h1>
<div class="categories">
    <table class="table">
        <thead>
        <tr>
            <th class="table--center">ID</th>
            <th class="table--large_column">Name</th>
            <th class="table--center table--small_column">Actions</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var category in Model.Categories)
        {
            <tr>
                <td class="table--center">@category.Id</td>
                <td class="table--large_column">@category.Name</td>
                <td class="table--center table--small_column">
                    <a class="button" asp-page="/Admin/CategoryPage" asp-route-id="@category.Id">Show details</a>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>

CraftHouse.Web/Pages/Admin/CategoryPage.cshtml
@page "/admin/category/{id}"
@model CraftHouse.Web.Pages.Admin.CategoryPage

@{
    ViewData["title"] = "Category";
    ViewData["styles"] = "categories";
}

<a class="return" asp-page="/admin/Categories">
    <img class="return__arrow" src="~/photos/arrow-left-solid.svg" alt="arrow"/>
    <p class="return__text">Return</p>
</a>

@if (Model.Error != null)
{
    <div class="error">@Model.Error</div>
}

<h1>Category @Model.Category.Name</h1>
<h2>Products in this category: @Model.Category.Products.Count</h2>

<form class="form" method="post" asp-page-handler="update">
    <label for="update-id">ID:</label>
    <input readonly id="update-id" type="number" asp-for="CategoryUpdate.Id" value="@Model.Category.Id"/>
    <label for="update-name">Name:</label>
    <input id="update-name" type="text" asp-for="CategoryUpdate.Name" value="@Model.Category.Name"/>
    <input class="button button--teal" type="submit" value="Update"/>
</form>

<form class="form" method="post" asp-page-handler="delete">
    <input type="hidden" asp-for="CategoryDelete.Id" value="@Model.Category!.Id"/>
    <input class="button button--red form--red" type="submit" value="Delete"/>
</form>

<h1>Products with this category</h1>
<table class="table">
    <thead>
    <th class="table--center table--xsmall_column">ID</th>
    <th>Name</th>
    </thead>
    <tbody>
    @foreach (var product in Model.Category.Products)
    {
        <tr>
            <td class="table--center table--xsmall_column">@product.Id</td>
            <td>@product.Name</td>
        </tr>
    }
    </tbody>
</table>

CraftHouse.Web/Pages/Admin/OptionValuesManagement.cshtml
@page "{optionId}"
@model CraftHouse.Web.Pages.Admin.OptionValuesManagement

@{
    ViewData["title"] = "Manage option values";
    ViewData["styles"] = "manageOptions";
}

<a class="return" asp-page="/admin/OptionsManagement" asp-route-productId="@Model.Option.ProductId" asp-route-optionNumber="1">
    <img class="return__arrow" src="~/photos/arrow-left-solid.svg" alt="arrow"/>
    <p class="return__text">Return</p>
</a>

<h1>Values for option @Model.Option.Name</h1>

@if (Model.Errors != null)
{
    @foreach (var error in @Model.Errors)
    {
    <div class="error">@error</div>
    }
}

<form class="form" method="post" asp-page-handler="OptionName">
    <label>Name</label>
    <input type="text" value="@Model.Option.Name" asp-for="OptionName"/>
    <input class="button button--teal" type="submit" value="Change"/>
</form>

<br/>

<form class="form"  method="post" asp-page-handler="NewValue">
    <input type="hidden" value="@Model.Option.ProductId"/>
    <label>Value</label>
    <input type="text" asp-for="@Model.OptionValueDto.Value"/>
    <label>Price</label>
    <input type="number" step="0.01" min="0" asp-for="@Model.OptionValueDto.Price"/>
    <input class="button button--teal" type="submit" value="Add"/>
</form>

<table class="table">
    <thead>
    <th class="table--center">Option ID</th>
    <th>Value</th>
    <th>Price</th>
    <th>New value</th>
    <th>New price</th>
    <th>Update</th>
    <th>Remove</th>
    </thead>
    <tbody>
    @foreach (var optionValue in @Model.OptionValues)
    {
        <tr>
            <td class="table--center">@optionValue.OptionId</td>
            <td>@optionValue.Value</td>
            <td>@optionValue.Price</td>
            <form method="post" asp-page-handler="UpdateValue">
                <input type="hidden" value="@optionValue.OptionId" asp-for="OptionId"/>
                <input type="hidden" value="@optionValue.Value" asp-for="OldOptionValue"/>
                <td>
                    <input type="text" value="@optionValue.Value" asp-for="OptionValue"/>
                </td>
                <td>
                    <input type="number" step="0.01" min="0" value="@optionValue.Price.ToString().Replace(",", ".")" asp-for="OptionPrice"/>
                </td>
                <td>
                    <input class="button" type="submit" value="Update"/>
                </td>
            </form>

            <td>
                <form method="post" asp-page-handler="Remove">
                    <input type="hidden" value="@optionValue.OptionId" asp-for="OptionId"/>
                    <input type="hidden" value="@optionValue.Value" asp-for="OptionValue"/>
                    <input class="button button--red" type="submit" value="Delete"/>
                </form>
            </td>
        </tr>
    }
    </tbody>
</table>

CraftHouse.Web/Pages/Admin/OptionsManagement.cshtml
@page "{productId}"
@model CraftHouse.Web.Pages.Admin.OptionsManagement

@{
    ViewData["title"] = "Manage options";
    ViewData["styles"] = "manageOptions";
}

<a class="return" asp-page="/admin/Products">
    <img class="return__arrow" src="~/photos/arrow-left-solid.svg" alt="arrow"/>
    <p class="return__text">Return</p>
</a>

@if (Model.Errors != null)
{
    @foreach (var error in @Model.Errors)
    {
        <div class="error">@error</div>
    }
}

<h1>Add option for product: @Model.Product.Name</h1>
<form class="form" method="post" asp-page-handler="Option">
    <input type="hidden" asp-for="ProductId" value="@Model.Product.Id"/>
    <input type="hidden" asp-for="OptionNumber" value="@Model.OptionNumber"/>

    <label for="name">Name</label>
    <input type="text" id="name" asp-for="Name"/>

    <label for="maxOccurs">Max occurs</label>
    <input type="number" id="maxOccurs" asp-for="MaxOccurs" value="1" min="1"/>

    @for (var i = 0; i < @Model.OptionNumber; i++)
    {
        <label>Option value</label>
        <input type="text" class="optionValue" asp-for="OptionValues"/>

        <label>Option price</label>
        <input type="number" step="0.01" class="optionPrice" asp-for="OptionPrices"/>
        <br/>
    }

    <div class="display_flex">
        @if (Model.OptionNumber - 1 > 0)
        {
            <a class="button button--red" asp-page="/admin/OptionsManagement" asp-route-productId="@Model.Product.Id" asp-route-optionNumber="@(Model.OptionNumber - 1)">Less options</a>
        }

        <a class="button" asp-page="/admin/OptionsManagement" asp-route-productId="@Model.Product.Id" asp-route-optionNumber="@(Model.OptionNumber + 1)">More options</a>
    </div>
    <input class="button button--teal" type="submit" value="Add option"/>
</form>

<table class="table">
    <thead>
    <th>ID</th>
    <th class="table--large_column">Name</th>
    <th class="table--small_column table--center">Max occurs</th>
    <th class="table--center">Actions</th>
    </thead>
    <tbody>
    @foreach (var option in Model.ExistingOptions)
    {
        <tr>
            <td>@option.Id</td>
            <td class="table--large_column">@option.Name</td>
            <td class="table--small_column table--center">@option.MaxOccurs</td>
            <td class="table--flex">
                <a class="button" asp-page="/admin/OptionValuesManagement" asp-route-optionId="@option.Id">Edit</a>
                <form method="post" asp-page-handler="Remove">
                    <input type="hidden" value="@option.Id" asp-for="DeleteOptionModel.Id"/>
                    <input class="button button--red" type="submit" value="Delete"/>
                </form>
            </td>
        </tr>
    }
    </tbody>
</table>

CraftHouse.Web/Pages/Admin/Products.cshtml
@page
@model ProductManagement

@{
    ViewData["title"] = "Products";
    ViewData["styles"] = "products";
}

@if (Model.Errors != null)
{
    @foreach (var error in @Model.Errors)
    {
        <div class="error">@error</div>
    }
}

<h1>Add new product</h1>
<form class="form" method="post" asp-page-handler="Product">
    <label for="name">Name</label>
    <input type="text" id="name" asp-for="@Model.ProductDto.Name"/>


    <label for="price">Price</label>
    <input type="number" step="0.01" id="price" asp-for="@Model.ProductDto.Price"/>

    <label for="description">Description</label>
    <textarea id="description" asp-for="@Model.ProductDto.Description" maxlength="250"></textarea>

    <label for="categoryId">Category name</label>
    <select id="categoryId" asp-for="@Model.ProductDto.CategoryId">
        @foreach (var category in Model.Categories)
        {
            <option value="@category.Id">@category.Name</option>
        }
    </select>

    <div>
        <input id="unavailable" type="radio" value="false" asp-for="@Model.ProductDto.IsAvailable" checked="checked"/>
        <label for="unavailable">Unavailable</label>
        <input id="available" type="radio" value="true" asp-for="@Model.ProductDto.IsAvailable"/>
        <label for="available">Available</label>
    </div>

    <input class="button button--teal" type="submit" value="Add"/>
</form>

<table class="table">
    <thead>
    <th class="table--center">ID</th>
    <th>Name</th>
    <th>Available</th>
    <th>Price</th>
    <th class="table--medium_column">Description</th>
    <th>Category</th>
    <th class="table--center">Actions</th>
    </thead>
    <tbody>
    @foreach (var product in @Model.Products)
    {
        <tr>
            <td class="table--center">@product.Id</td>
            <td>@product.Name</td>
            <td>@product.IsAvailable</td>
            <td>@product.Price</td>
            <td class="table--medium_column">@product.Description</td>
            <td>@product.Category.Name</td>
            <td class="table--flex">
                <a class="button" asp-page="/admin/ProductPage" asp-route-productId="@product.Id">Edit product</a>
                <a class="button" asp-page="/admin/OptionsManagement" asp-route-productId="@product.Id" asp-route-optionNumber="1">Manage options</a>
                <form method="post" asp-page-handler="Remove">
                    <input type="hidden" value="@product.Id" asp-for="ProductId"/>
                    <input class="button button--red" type="submit" value="Delete"/>
                </form>
            </td>
        </tr>
    }
    </tbody>
</table>