CraftHouse.Web/Entities/Order.cs
using System.ComponentModel.DataAnnotations;

namespace CraftHouse.Web.Entities;

public class Order : EntityBase
{
    [Key]
    public int Id { get; set; }

    [Required]
    public float Value { get; set; }

    [Required]
    public OrderStatus OrderStatus { get; set; } = OrderStatus.Created;

    [Required]
    public string Telephone { get; set; } = null!;

    [Required]
    public string City { get; set; } = null!;

    [Required]
    public string PostalCode { get; set; } = null!;

    [Required]
    public string AddressLine { get; set; } = null!;

    public string? Comment { get; set; }

    [Required]
    public int UserId { get; set; }
    public User User { get; set; } = null!;

    public ICollection<OrderItem> OrderItems { get; set; } = null!;
}

public enum OrderStatus {
    Created,
    Pending,
    Preparation,
    Shipping,
    Finished,
    Canceled
}

CraftHouse.Web/Pages/Admin/Orders.cshtml.cs
using CraftHouse.Web.Entities;
using CraftHouse.Web.Infrastructure;
using CraftHouse.Web.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CraftHouse.Web.Pages.Admin;

[RequireAuth(UserType.Administrator)]
public class Orders : PageModel
{
    private readonly IOrderRepository _orderRepository;
    private readonly IUserRepository _userRepository;
    private readonly ILogger<Orders> _logger;

    public Orders(IOrderRepository orderRepository, IUserRepository userRepository, ILogger<Orders> logger)
    {
        _orderRepository = orderRepository;
        _userRepository = userRepository;
        _logger = logger;
    }
    
    [BindProperty]
    public int? UserId { get; set; }

    public List<Order> OrdersList { get; set; }

    public List<Entities.User> Users { get; set; }

    public string? OrderBy { get; set; }
    public bool? IsAscending { get; set; } = false;

    public async Task<IActionResult> OnGetAsync(int? userId, string? orderBy, bool? isAscending,
        CancellationToken cancellationToken)
    {
        OrderBy = orderBy;
        IsAscending = isAscending;
        IsAscending ??= false;

        if (userId is not null)
        {
            UserId = userId;
            var user = await _userRepository.GetUserByIdAsync((int)UserId, cancellationToken);

            if (user is null)
            {
                throw new NullReferenceException("User does not exists");
            }

            OrdersList =
                await _orderRepository.GetOrdersByUserIdWithSortingAsync((int)UserId, OrderBy, IsAscending,
                    cancellationToken);
        }
        else
        {
            OrdersList = await _orderRepository.GetOrdersWithSortingAsync(OrderBy, IsAscending, cancellationToken);
        }

        Users = await _userRepository.GetAllUsersAsync(cancellationToken);

        return Page();
    }
}

CraftHouse.Web/Pages/CategoryManagement.cshtml.cs
using CraftHouse.Web.Data;
using CraftHouse.Web.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CraftHouse.Web.Pages;

public class CategoryManagement : PageModel
{
    private readonly AppDbContext _context;

    public CategoryManagement(AppDbContext context)
    {
        _context = context;
    }

    [BindProperty]
    public int CategoryId { get; set; }

    public List<Category> Categories { get; set; } = null!;

    public List<Product> Products { get; set; } = null!;

    public string? Error { get; set; } = null;

    [BindProperty]
    public string CategoryName { get; set; } = null!;

    private bool CategoryExists(string name) 
        => _context.Categories.Any(x => x.Name == name);

    public void OnGet()
    {
        Categories = _context.Categories.Where(x => x.DeletedAt == null).ToList();
        Products = _context.Products.ToList();
    }

    public async Task<IActionResult> OnPostDeleteCategoryAsync()
    {
        var containsProducts =
            _context.Products.Any(product => product.CategoryId == CategoryId && product.DeletedAt == null);

        var category = _context.Categories.FirstOrDefault(x => x.Id == CategoryId);

        if (containsProducts || category == null)
        {
            Categories = _context.Categories.Where(x => x.DeletedAt == null).ToList();
            Error = "You can not delete category when any product is in it";
            if (category == null)
            {
                Error = "This category does not exists";
            }
            return Page();
        }

        category.DeletedAt = DateTime.Now;

        _context.Categories.Update(category);
        await _context.SaveChangesAsync();

        return Redirect("/CategoryManagement");
    }

    public async Task<IActionResult> OnPostAddCategoryAsync()
    {
        if (CategoryName.Length < 3 || CategoryExists(CategoryName))
        {
            Error = "That named category already exits";
            if (CategoryName.Length < 3)
            {
                Error = "Incorrect category name";
            }
            Categories = _context.Categories.Where(x => x.DeletedAt == null).ToList();
            CategoryName = "";
            return Page();
        }

        var category = new Category()
        {
            Name = CategoryName
        };

        await _context.Categories.AddAsync(category);
        await _context.SaveChangesAsync();

        return Redirect("/CategoryManagement");
    }

    public async Task<IActionResult> OnPostRenameCategoryAsync()
    {
        if (CategoryName.Length < 3 || CategoryExists(CategoryName))
        {
            Error = "That named category already exits";
            if (CategoryName.Length < 3)
            {
                Error = "Incorrect category name";
            }
            Categories = _context.Categories.Where(x => x.DeletedAt == null).ToList();
            CategoryName = "";
            return Page();
        }

        var category = _context.Categories.FirstOrDefault(x => x.Id == CategoryId);

        if (category == null)
        {
            Error = "This category does not exists";
            return Page();
        }

        category.Name = CategoryName;
        _context.Categories.Update(category);
        await _context.SaveChangesAsync();

        return Redirect("/CategoryManagement");
    }
}

CraftHouse.Web/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CraftHouse.Web.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

CraftHouse.Web/Pages/Index.cshtml.cs
using CraftHouse.Web.Entities;
using CraftHouse.Web.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CraftHouse.Web.Pages;

public class IndexModel : PageModel
{
    private readonly ICategoryRepository _categoryRepository;
    private readonly IProductRepository _productRepository;

    public IndexModel(ICategoryRepository categoryRepository,
        ILogger<IndexModel> logger, IProductRepository productRepository)
    {
        _categoryRepository = categoryRepository;
        _productRepository = productRepository;
    }

    public int? CategoryId { get; set; }
    public int PageNumber { get; set; }
    public string? Order { get; set; }
    public bool? IsAscending { get; set; }
    public List<Category> Categories { get; set; } = null!;
    public List<Product> Products { get; set; } = null!;

    public async Task<IActionResult> OnGetAsync(int pageNumber, int? category, string? order, bool? isAscending,
        CancellationToken cancellationToken)
    {
        if (pageNumber <= 0)
        {
            throw new InvalidOperationException("Page does not exists");
        }

        CategoryId = category;
        Categories = await _categoryRepository.GetCategoriesAsync(cancellationToken);
        PageNumber = pageNumber;
        Order = order;
        IsAscending = isAscending;
        const int productsPerPage = 15;

        var productCount = await _productRepository.GetProductsCountByCategoryAsync(CategoryId, cancellationToken);

        Products = await _productRepository
            .GetProductsByCategoryWithSortingAsync(
                pageNumber,
                CategoryId,
                Order,
                IsAscending,
                cancellationToken);

        ViewData["lastPageNumber"] = 1 + productCount / productsPerPage;

        if (Products.Count == 0 && pageNumber > 1)
        {
            throw new InvalidOperationException("Page does not exists");
        }

        return Page();
    }
}

CraftHouse.Web/Pages/Login.cshtml.cs
using CraftHouse.Web.Repositories;
using CraftHouse.Web.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CraftHouse.Web.Pages;

public class Login : PageModel
{
    private readonly IAuthService _authService;
    private readonly IUserRepository _userRepository;

    public Login(IAuthService authService, IUserRepository userRepository)
    {
        _authService = authService;
        _userRepository = userRepository;
    }

    [BindProperty]
    public LoginUserModel LoginUser { get; set; } = new();

    public string? Error { get; set; }

    public void OnGet([FromQuery] string redirectUrl)
    {
        LoginUser.ReturnUrl = redirectUrl;
    }

    public async Task<IActionResult> OnPostAsync(CancellationToken cancellationToken)
    {
        var user = await _userRepository.GetUserByEmailAsync(LoginUser.Email, cancellationToken);
        if (user is null)
        {
            Error = "Provided email and password combination is invalid. Try again!";
            return Page();
        }

        var result = _authService.Login(user, LoginUser.Password);
        if (result)
        {
            return Redirect(LoginUser.ReturnUrl ?? "/");
        }

        Error = "Provided email and password combination is invalid. Try again!";
        return Page();
    }
}

public class LoginUserModel
{
    public string Email { get; init; } = null!;
    public string Password { get; init; } = null!;
    public string? ReturnUrl { get; set; }
};

CraftHouse.Web/Pages/Logout.cshtml.cs
using CraftHouse.Web.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CraftHouse.Web.Pages;

public class Logout : PageModel
{
    private readonly IAuthService _authService;

    public Logout(IAuthService authService)
    {
        _authService = authService;
    }
    public IActionResult OnGet()
    {
       _authService.Logout();
       return RedirectToPage("index");
    }
}

CraftHouse.Web/Pages/Order.cshtml.cs
using CraftHouse.Web.Entities;
using CraftHouse.Web.Infrastructure;
using CraftHouse.Web.Repositories;
using CraftHouse.Web.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CraftHouse.Web.Pages;

[RequireAuth]
public class OrderModel : PageModel
{
    private readonly IAuthService _authService;
    private readonly ICartService _cartService;
    private readonly IOrderRepository _orderRepository;
    private readonly ILogger<OrderModel> _logger;

    public OrderModel(IAuthService authService, ICartService cartService,
        IOrderRepository orderRepository, ILogger<OrderModel> logger)
    {
        _authService = authService;
        _cartService = cartService;
        _orderRepository = orderRepository;
        _logger = logger;
    }

    [BindProperty]
    public CreateOrderModel CreateOrder { get; set; } = null!;

    public User UserData { get; set; } = null!;

    public float CartValue { get; set; }
    public float ShippingCost { get; set; } = 0.0f;

    public float OrderValue
        => CartValue + ShippingCost;

    public async Task OnGetAsync(CancellationToken cancellationToken)
    {
        var user = await _authService.GetLoggedInUserAsync(cancellationToken);
        UserData = user ?? throw new InvalidOperationException("User cannot be null");

        var cart = _cartService.GetCartEntries();
        CartValue = await _orderRepository.CalculateCartValueAsync(cart, cancellationToken);
    }

    public async Task<IActionResult> OnPostAsync(CancellationToken cancellationToken)
    {
        _logger.LogInformation("Model: {@model}", CreateOrder);
        var cart = _cartService.GetCartEntries().ToList();
        if (!cart.Any())
        {
            throw new InvalidOperationException("Cannot place order with no items");
        }

        var user = await _authService.GetLoggedInUserAsync(cancellationToken);
        UserData = user ?? throw new InvalidOperationException("User cannot be null");

        var order = new Order()
        {
            UserId = UserData.Id,
            AddressLine = CreateOrder.AddressLine,
            City = CreateOrder.City,
            PostalCode = CreateOrder.Postal,
            Telephone = CreateOrder.Telephone,
            Comment = CreateOrder.Comment
        };

        await _orderRepository.CreateOrderAsync(order, cart, cancellationToken);

        _cartService.ClearCart();

        return Redirect("/Index");
    }
}

public record CreateOrderModel(string AddressLine, string City, string Postal, string Telephone, string Comment);

CraftHouse.Web/Pages/OrderDetails.cshtml.cs
using CraftHouse.Web.Entities;
using CraftHouse.Web.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CraftHouse.Web.Pages;

public class OrderDetails : PageModel
{
    private readonly IOrderItemRepository _orderItemRepository;
    private readonly IOrderItemOptionRepository _orderItemOptionRepository;

    public int OrderId { get; set; }
    public List<OrderItem> OrderItems { get; set; } = null!;
    public List<OrderItemOption> OrderItemOptions { get; set; } = null!;

    public OrderDetails(IOrderItemRepository orderItemRepository, IOrderItemOptionRepository orderItemOptionRepository)
    {
        _orderItemRepository = orderItemRepository;
        _orderItemOptionRepository = orderItemOptionRepository;
    }

    public async Task<IActionResult> OnGet(int orderId, CancellationToken cancellationToken)
    {
        OrderId = orderId;
        OrderItems = await _orderItemRepository.GetOrderItemByOrderIdAsync(orderId, cancellationToken);
        OrderItemOptions = new List<OrderItemOption>();
        foreach (var orderItem in OrderItems)
        {
            OrderItemOptions.AddRange(
                await _orderItemOptionRepository.GetOrderItemOptionByOrderItemIdAsync(orderItem.Id, cancellationToken));
        }

        return Page();
    }
}

CraftHouse.Web/Pages/Registration.cshtml.cs
using CraftHouse.Web.DTOs;
using CraftHouse.Web.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CraftHouse.Web.Pages;

public class Registration : PageModel
{
    private readonly IUserRepository _userRepository;

    public Registration(IUserRepository userRepository)
    {
        _userRepository = userRepository;
    }

    [BindProperty]
    public RegisterUserDto UserRegister { get; set; } = null!;

    public List<string>? ValidationErrors { get; set; }

    public void OnGet()
    {
    }

    public async Task<IActionResult> OnPostAsync(CancellationToken cancellationToken)
    {
        var user = UserRegister.MapToUser();

        if (UserRegister.Password != UserRegister.ConfirmPassword)
        {
            ValidationErrors = new List<string> { "Passwords do not match" };
        }

        var result = await _userRepository.CreateUserAsync(user, UserRegister.Password, cancellationToken);
        if (result.Succeeded)
        {
            return RedirectToPage("/Index");
        }
        ValidationErrors = result.Errors;
        return Page();
    }
}

CraftHouse.Web/Pages/Seed.cshtml.cs
using CraftHouse.Web.Data;
using CraftHouse.Web.Entities;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CraftHouse.Web.Pages;

public class Seed : PageModel
{
    private readonly AppDbContext _context;

    public Seed(AppDbContext context)
    {
        _context = context;
    }

    public async Task OnGetAsync()
    {
        var categories = new List<Category>()
        {
            new() { Name = "Test" },
            new() { Name = "Test2" }
        };

        _context.Categories.AddRange(categories);

        var products = new List<Product>();

        for (var i = 0; i < 50; i++)
        {
            var product = new Product()
            {
                CategoryId = 2,
                Name = $"Test Product #{i}",
                Price = 15.99f,
                Description = $"Test product Description #{i}"
            };
            products.Add(product);
        }

        _context.Products.AddRange(products);

        await _context.SaveChangesAsync();
    }
}

CraftHouse.Web/Pages/CategoryManagement.cshtml
@page
@using CraftHouse.Web.Entities
@model CraftHouse.Web.Pages.CategoryManagement


@if (Model.Error != null)
{
    <div class="error">@Model.Error</div>
}

<div class="categories__title">Current categories</div>
<div class="categories">
    @foreach (var category in Model.Categories)
    {
        <div class="categories__category">
            <div class="categories__id">@category.Id</div>
            <div class="categories__name">@category.Name</div>
            <form method="post" asp-page-handler="DeleteCategory">
                <input type="submit" value="Delete" class="categories__delete-button"/>
                <input type="hidden" value="@category.Id" asp-for="CategoryId">
            </form>
        </div>
    }
</div>

<form method="post" asp-page-handler="AddCategory" class="categoryManagement__form">
    <label for="addCategoryName">Name for new category</label>
    <input type="text" id="addCategoryName" asp-for="CategoryName"/>

    <input type="submit" value="Add"/>
</form>

<form method="post" asp-page-handler="RenameCategory" class="categoryManagement__form">
    <label for="renameCategory">Rename category</label>
    <select id="renameCategory" asp-for="CategoryId">
        @foreach (var category in Model.Categories)
        {
            <option value="@category.Id">@category.Id. @category.Name</option>
        }
    </select>
    <input type="text" asp-for="CategoryName"/>

    <input type="submit" value="Rename"/>
</form>

CraftHouse.Web/Pages/Index.cshtml
@page "{pageNumber:int=1}"
@using Microsoft.EntityFrameworkCore
@model IndexModel
@{
    ViewData["Title"] = "Home page";
    ViewData["styles"] = "index";
}

<div class="container">
    <aside class="nav">
        @if (Model.Products.Count > 1)
        {
            <p class="nav__header">Sort by</p>
            @foreach (var sortValue in new[] { "name", "price" })
            {
                if (Model.Order != null && Model.Order.Equals(sortValue) && Model.IsAscending != false)
                {
                    <a class="nav__order nav__order--chosen" asp-page="/Index"
                       asp-route-pageNumber="1"
                       asp-route-category="@Model.CategoryId"
                       asp-route-order="@sortValue">
                        @sortValue
                    </a>
                }
                else
                {
                    <a class="nav__order" asp-page="/Index"
                       asp-route-pageNumber="1"
                       asp-route-category="@Model.CategoryId"
                       asp-route-order="@sortValue">
                        @sortValue
                    </a>
                }
                if (Model.Order != null && Model.Order.Equals(sortValue) && Model.IsAscending == false)
                {
                    <a class="nav__order nav__order--chosen" asp-page="/Index"
                       asp-route-pageNumber="1"
                       asp-route-category="@Model.CategoryId"
                       asp-route-order="@sortValue"
                       asp-route-isAscending="false">
                        @sortValue descending
                    </a>
                }
                else
                {
                    <a class="nav__order" asp-page="/Index"
                       asp-route-pageNumber="1"
                       asp-route-category="@Model.CategoryId"
                       asp-route-order="@sortValue"
                       asp-route-isAscending="false">
                        @sortValue descending
                    </a>
                }
            }
        }
        
        <p class="nav__header">Categories</p>
        @if (Model.CategoryId == null)
        {
            <a class="nav__category nav__category--chosen" asp-page="/Index" asp-route-pageNumber="1">All</a>
        }
        else
        {
            <a class="nav__category" asp-page="/Index" asp-route-pageNumber="1">All</a>
        }
        @foreach (var category in Model.Categories)
        {
            if (Model.CategoryId == category.Id)
            {
                <a class="nav__category nav__category--chosen" asp-page="/Index"
                   asp-route-pageNumber="1"
                   asp-route-category="@category.Id">
                    @category.Name
                </a>
            }
            else
            {
                <a class="nav__category" asp-page="/Index"
                   asp-route-pageNumber="1"
                   asp-route-category="@category.Id">
                    @category.Name
                </a>
            }
        }
    </aside>

    <div class="products">
        @foreach (var prod in Model.Products)
        {
            <div class="products__product product">
                <img class="product__photo" src="~/photos/pexels-irina-varanovich-14686152.jpg" alt="Product image"/>
                <div class="product__block-main">
                    <p class="product__name">@prod.Name</p>
                    <p class="product__description">@prod.Description</p>
                </div>
                <div class="product__block-add">
                    <a class="product__button button button--red" asp-page="/Cart/Add" asp-route-productId="@prod.Id">Add to cart</a>
                    <p class="product__price">@prod.Price</p>
                </div>
            </div>
        }
    </div>
    <div class="products__pagination">
        @if (Model.PageNumber != 1)
        {
            <a asp-page="/Index"
               asp-route-pageNumber="@(Model.PageNumber - 1)"
               asp-route-category="@Model.CategoryId"
               asp-route-order="@Model.Order"
               asp-route-isAscending="@Model.IsAscending">
                Prev Page
            </a>
        }
        <span>@Model.PageNumber</span>
        @if ((int)Model.ViewData["lastPageNumber"]! != Model.PageNumber)
        {
            <a asp-page="/Index"
               asp-route-pageNumber="@(Model.PageNumber + 1)"
               asp-route-category="@Model.CategoryId"
               asp-route-order="@Model.Order"
               asp-route-isAscending="@Model.IsAscending">
                Next Page
            </a>
        }
    </div>
</div>

CraftHouse.Web/Pages/Login.cshtml
@page
@model CraftHouse.Web.Pages.Login
@{
    ViewData["title"] = "Login";
    ViewData["styles"] = "login";
    ViewData["no_render_nav"] = true;
}

<div class="container">
    <div class="logo">
        <a asp-page="/Index">Craft House</a>
    </div>
    <h1>Login</h1>
    @if (Model.Error is not null)
    {
        <div class="login__error">
            @Model.Error
        </div>
    }
    <form method="post">
        <div class="form__group">
            <input class="form__input" type="text" id="email" asp-for="LoginUser.Email"/>
            <label class="form__label" for="email">E-mail address</label>
        </div>
        <div class="form__group">
            <input class="form__input" type="password" id="password" asp-for="LoginUser.Password"/>
            <label class="form__label" for="password">Password</label>
        </div>

        <input type="hidden" value="@Model.LoginUser.ReturnUrl" asp-for="LoginUser.ReturnUrl"/>
        
        <div class="form__links">
            <a asp-page="/Registration">Create account</a>
            <a asp-page="/Registration">Forgot password</a>
        </div>

        <input class="form__submit" type="submit" value="Login"/>
    </form>
</div>

CraftHouse.Web/Pages/Logout.cshtml
@page
@model CraftHouse.Web.Pages.Logout

CraftHouse.Web/Pages/Order.cshtml
@page
@using System.Globalization
@model CraftHouse.Web.Pages.OrderModel
@{
    ViewData["title"] = "Order";
    ViewData["styles"] = "order";
}

<div class="order-grid">
    <div class="order__header">
        <h1>Finish placing order</h1>
    </div>
    <div class="order__form">
        <h2 class="order__h2">Shipping information</h2>
        <form class="form" method="post">
            <label asp-for="CreateOrder.AddressLine">Address line</label>
            <input class="form--red" type="text" asp-for="CreateOrder.AddressLine" value="@Model.UserData.AddressLine"/>
            <label asp-for="CreateOrder.City">City</label>
            <input class="form--red" type="text" asp-for="CreateOrder.City" value="@Model.UserData.City"/>
            <label asp-for="CreateOrder.Postal">Postal code</label>
            <input class="form--red" type="text" asp-for="CreateOrder.Postal" value="@Model.UserData.PostalCode"/>
            <label asp-for="CreateOrder.Telephone">Telephone</label>
            <input class="form--red" type="text" asp-for="CreateOrder.Telephone" value="@Model.UserData.TelephoneNumber"/>
            <label asp-for="CreateOrder.Comment">Add a comment to your order</label>
            <textarea asp-for="CreateOrder.Comment" class="form--red"></textarea>
            <input class="button button--red form--red" type="submit" value="Place Order"/>
        </form>
    </div>
    <div class="order__summary">
        <h2 class="order__h2">Summary</h2>
        <div class="summary__line">
            <div>Order value:</div>
            <div>@Model.CartValue.ToString("c2")</div>
        </div>
        <div class="summary__line">
            <div>Shipping cost:</div>
            <div>@Model.ShippingCost.ToString("c2")</div>
        </div>
        <div class="summary__spacer"></div>
        <div class="summary__line">
            <div>Total cost:</div>
            <div>@Model.OrderValue.ToString("c2")</div>
        </div>
    </div>
</div>

CraftHouse.Web/Pages/OrderDetails.cshtml
@page "{orderId}"
@using CraftHouse.Web.Entities
@model CraftHouse.Web.Pages.OrderDetails

@{
    ViewData["title"] = "Order details";
    ViewData["styles"] = "orders";
}

<h1>Details for order #@Model.OrderId</h1>
@foreach (var orderItem in @Model.OrderItems)
{
    <table class="table">
        <thead>
        <th class="table--center">ID</th>
        <th>Product category</th>
        <th>Product name</th>
        <th>Value</th>
        </thead>

        <tbody>
        <tr>
            <td class="table--center">@orderItem.Id</td>
            <td>@orderItem.Product.Category.Name</td>
            <td>@orderItem.Product.Name</td>
            <td>@orderItem.Value</td>
        </tr>
        @if (@Model.OrderItemOptions.Any(x => x.OrderItemId == orderItem.Id))
        {
            <thead>
            <th class="table--center table--light_red_background">ID</th>
            <th class="table--light_red_background">Option name</th>
            <th class="table--light_red_background">Option value</th>
            <th class="table--light_red_background"></th>
            </thead> 
            @foreach (var option in @Model.OrderItemOptions.Where(x => x.OrderItemId == orderItem.Id))
            {
                <tr>
                    <td class="table--center">@option.Id</td>
                    <td>@option.Name</td>
                    <td>@option.Value</td>
                    <td></td>
                </tr>
            }
        }
        </tbody>
    </table>
}

CraftHouse.Web/Pages/Registration.cshtml
@page
@model CraftHouse.Web.Pages.Registration
@{
    ViewData["no_render_nav"] = true;
    ViewData["title"] = "Register";
    ViewData["styles"] = "login";
}

<div class="container margin-top">
    <div class="logo">
        <a asp-page="/Index">Craft House</a>
    </div>
    <h1>Create account</h1>
    @if (Model.ValidationErrors != null)
    {
        <div class="form__error">
            @foreach (var error in Model.ValidationErrors)
            {
                <p>@error</p>
            }
        </div>
    }
    <form method="post">
        <div class="form__group">
            <input class="form__input" type="text" id="firstName" asp-for="UserRegister.FirstName"/>
            <label class="form__label" for="firstName">First Name</label>
        </div>
        <div class="form__group">
            <input class="form__input" type="text" id="lastName" asp-for="UserRegister.LastName"/>
            <label class="form__label" for="lastName">Last Name</label>
        </div>
        <div class="form__group">
            <input class="form__input" type="number" id="telephoneNumber" asp-for="UserRegister.TelephoneNumber"/>
            <label class="form__label" for="telephoneNumber">Telephone number</label>
        </div>
        <div class="form__group">
            <input class="form__input" type="text" id="city" asp-for="UserRegister.City"/>
            <label class="form__label" for="city">City</label>
        </div>
        <div class="form__group">
            <input class="form__input" type="text" id="postalCode" asp-for="UserRegister.PostalCode"/>
            <label class="form__label" for="postalCode">Postal code</label>
        </div>
        <div class="form__group">
            <input class="form__input" type="text" id="addressLine" asp-for="UserRegister.AddressLine"/>
            <label class="form__label" for="addressLine">Address</label>
        </div>
        <div class="form__group">
            <input class="form__input" type="text" id="email" asp-for="UserRegister.Mail"/>
            <label class="form__label" for="email">E-mail address</label>
        </div>
        <div class="form__group">
            <input class="form__input" type="password" id="password" asp-for="UserRegister.Password"/>
            <label class="form__label" for="password">Password</label>
        </div>
        <div class="form__group">
            <input class="form__input" type="password" id="confirmPassword" asp-for="UserRegister.ConfirmPassword"/>
            <label class="form__label" for="confirmPassword">Confirm password</label>
        </div>

        <input class="form__submit" type="submit" value="Register"/>
    </form>

</div>

CraftHouse.Web/Pages/Seed.cshtml
@page
@model CraftHouse.Web.Pages.Seed