CraftHouse.Web/Pages/Account/Index.cshtml.cs
using CraftHouse.Web.Entities;
using CraftHouse.Web.Infrastructure;
using CraftHouse.Web.Repositories;
using CraftHouse.Web.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CraftHouse.Web.Pages.Account;

[RequireAuth]
public class IndexModel : PageModel
{
    private readonly IAuthService _authService;
    private readonly IUserRepository _userRepository;
    private readonly IOrderRepository _orderRepository;

    public IndexModel(IAuthService authService, IUserRepository userRepository, IOrderRepository orderRepository)
    {
        _authService = authService;
        _userRepository = userRepository;
        _orderRepository = orderRepository;
    }

    [BindProperty]
    public UpdatePasswordModel UpdatePassword { get; set; } = null!;
    
    public User UserData { get; set; } = null!;

    public List<string> Errors { get; set; } = new();

    public  List<Order> Orders { get; set; }

    public async Task OnGetAsync(CancellationToken cancellationToken)
    {
        UserData = (await _authService.GetLoggedInUserAsync(cancellationToken))!;
        Orders = (await _orderRepository.GetOrdersByUserIdAsync(UserData.Id, cancellationToken));
    }

    public async Task<IActionResult> OnPostPasswordAsync(CancellationToken cancellationToken)
    {
        UserData = (await _authService.GetLoggedInUserAsync(cancellationToken))!;

        var passwordCorrect = _authService.VerifyUserPassword(UserData, UpdatePassword.OldPassword);
        if (!passwordCorrect)
        {
            Errors.Add("Wrong password");
            return Page();
        }

        if (UpdatePassword.Password != UpdatePassword.Password2)
        {
            Errors.Add("Passwords are not the same");
            return Page();
        }

        await _userRepository.UpdateUserPasswordAsync(UserData, UpdatePassword.Password, cancellationToken);
        return Redirect("/account");
    }
}

public record UpdatePasswordModel(string OldPassword, string Password, string Password2);

CraftHouse.Web/Pages/Account/Index.cshtml
@page "{handler?}"
@using CraftHouse.Web.Entities
@model CraftHouse.Web.Pages.Account.IndexModel

@{
    ViewData["title"] = "My account";
    ViewData["styles"] = "orders";
}

@foreach (var error in Model.Errors)
{
    <p class="error">@error</p>
}

<h1>@Model.UserData.FirstName @Model.UserData.LastName account</h1>

<form class="form form--red" method="post" asp-page-handler="password">
    <h2>Change password</h2>
    <label for="currentPassword">Current password</label>
    <input class="form--red" type="password" id="currentPassword" asp-for="UpdatePassword.OldPassword"/>
    <label for="newPassword">New password</label>
    <input class="form--red" type="password" id="newPassword" asp-for="UpdatePassword.Password"/>
    <label for="repeatPassword">Repeat new password</label>
    <input class="form--red" type="password" id="repeatPassword" asp-for="UpdatePassword.Password2"/>
    <input class="button button--red form--red" type="submit" value="Change password"/>
</form>


<h1>Orders</h1>
<table class="table">
    <thead>
    <th class="table--center">ID</th>
    <th class="table--medium_column">Price</th>
    <th>Status</th>
    <th class="table--medium_column">Order date</th>
    <th class="table--small_column table--center">Actions</th>
    </thead>
    <tbody>
    @foreach (var order in @Model.Orders)
    {
        if (@order.OrderStatus == OrderStatus.Canceled)
        {
            <tr class="table--light_red_background">
                <td class="table--center">@order.Id</td>
                <td>@order.Value</td>
                <td>@order.OrderStatus</td>
                <td>@order.CreatedAt</td>
                <td class="table--center">
                    <a class="button" asp-page="/OrderDetails" asp-route-orderId="@order.Id">Show details</a>
                </td>
            </tr>
        } else if (@order.OrderStatus == OrderStatus.Finished)
        {
            <tr class="table--light_blue_background">
                <td class="table--center">@order.Id</td>
                <td>@order.Value</td>
                <td>@order.OrderStatus</td>
                <td>@order.CreatedAt</td>
                <td class="table--center">
                    <a class="button" asp-page="/OrderDetails" asp-route-orderId="@order.Id">Show details</a>
                </td>
            </tr>
        }
        else
        {
            <tr>
                <td class="table--center">@order.Id</td>
                <td>@order.Value</td>
                <td>@order.OrderStatus</td>
                <td>@order.CreatedAt</td>
                <td class="table--center">
                    <a class="button" asp-page="/OrderDetails" asp-route-orderId="@order.Id">Show details</a>
                </td>
            </tr>
        }
        
    }
    </tbody>
</table>